import { OrganicContentAsset } from "@/types/organic";

export const demoOrganicAssets: OrganicContentAsset[] = [
  {
    id: "organic-001",
    platform: "TikTok",
    format: "video",
    duration: 15,
    creativeSignals: {
      hookStyle: "Fast Hook",
      visualFocus: "person",
      pacing: "fast",
      emotionalTone: "entertaining",
    },
    publishDate: "2024-01-15",
    title: "Quick Tutorial: Morning Routine",
  },
  {
    id: "organic-002",
    platform: "YouTube",
    format: "video",
    duration: 480,
    creativeSignals: {
      hookStyle: "Story Hook",
      visualFocus: "scene",
      pacing: "slow",
      emotionalTone: "informative",
    },
    publishDate: "2024-01-20",
    title: "Deep Dive: Content Strategy",
  },
  {
    id: "organic-003",
    platform: "Meta",
    format: "image",
    creativeSignals: {
      hookStyle: "Visual Hook",
      visualFocus: "product",
      emotionalTone: "inspiring",
    },
    publishDate: "2024-01-25",
    title: "Product Showcase",
  },
  {
    id: "organic-004",
    platform: "TikTok",
    format: "video",
    duration: 30,
    creativeSignals: {
      hookStyle: "Question Hook",
      visualFocus: "person",
      pacing: "fast",
      emotionalTone: "entertaining",
    },
    publishDate: "2024-02-01",
    title: "Q&A Session",
  },
  {
    id: "organic-005",
    platform: "YouTube",
    format: "video",
    duration: 300,
    creativeSignals: {
      hookStyle: "Problem-Solution",
      visualFocus: "scene",
      pacing: "medium",
      emotionalTone: "informative",
    },
    publishDate: "2024-02-05",
    title: "How to Solve X Problem",
  },
  {
    id: "organic-006",
    platform: "Meta",
    format: "video",
    duration: 60,
    creativeSignals: {
      hookStyle: "Emotional Hook",
      visualFocus: "person",
      pacing: "medium",
      emotionalTone: "inspiring",
    },
    publishDate: "2024-02-10",
    title: "Success Story",
  },
  {
    id: "organic-007",
    platform: "TikTok",
    format: "video",
    duration: 20,
    creativeSignals: {
      hookStyle: "Trend Hook",
      visualFocus: "person",
      pacing: "fast",
      emotionalTone: "entertaining",
    },
    publishDate: "2024-02-15",
    title: "Trending Challenge",
  },
  {
    id: "organic-008",
    platform: "YouTube",
    format: "video",
    duration: 600,
    creativeSignals: {
      hookStyle: "Educational Hook",
      visualFocus: "scene",
      pacing: "slow",
      emotionalTone: "informative",
    },
    publishDate: "2024-02-20",
    title: "Complete Guide Tutorial",
  },
];

