import { MomentContext } from "@/types/trend";

export const demoMoments: MomentContext[] = [
  {
    id: "moment-001",
    topic: "New Year Resolution Content",
    description: "Peak interest in productivity, fitness, and self-improvement content",
    startDate: "2024-01-01",
    endDate: "2024-01-31",
    intensityLevel: "high",
    category: "seasonal",
    relatedKeywords: ["new year", "resolution", "productivity", "fitness", "self-improvement", "goals"],
  },
  {
    id: "moment-002",
    topic: "Morning Routine Trend",
    description: "Viral morning routine content across TikTok and Instagram",
    startDate: "2024-01-10",
    endDate: "2024-01-25",
    intensityLevel: "high",
    category: "trending",
    relatedKeywords: ["morning routine", "productivity", "wellness", "self-care", "daily habits"],
  },
  {
    id: "moment-003",
    topic: "Valentine's Day Content",
    description: "Romantic and relationship-focused content surge",
    startDate: "2024-02-01",
    endDate: "2024-02-14",
    intensityLevel: "medium",
    category: "seasonal",
    relatedKeywords: ["valentine", "love", "relationship", "romance", "couples"],
  },
  {
    id: "moment-004",
    topic: "Content Strategy Deep Dive",
    description: "Increased interest in educational content marketing content",
    startDate: "2024-01-15",
    endDate: "2024-02-15",
    intensityLevel: "medium",
    category: "platform-native",
    relatedKeywords: ["content strategy", "marketing", "education", "tutorial", "how-to"],
  },
  {
    id: "moment-005",
    topic: "Product Launch Season",
    description: "Q1 product launches and showcases",
    startDate: "2024-01-20",
    endDate: "2024-03-31",
    intensityLevel: "low",
    category: "seasonal",
    relatedKeywords: ["product launch", "new product", "showcase", "announcement"],
  },
  {
    id: "moment-006",
    topic: "TikTok Challenge Wave",
    description: "Viral challenge content gaining momentum",
    startDate: "2024-02-10",
    endDate: "2024-02-20",
    intensityLevel: "high",
    category: "trending",
    relatedKeywords: ["challenge", "trend", "viral", "dance", "comedy"],
  },
];

