import { CompetitorContentAsset } from "@/types/competitor";

export const demoCompetitorContent: CompetitorContentAsset[] = [
  {
    assetId: "comp-asset-001",
    competitorId: "comp-001",
    platform: "Instagram",
    format: "image",
    publishDate: "2024-01-10",
    creativeSignals: {
      visualFocus: "product",
      hookStyle: "Lifestyle Showcase",
      narrativeAngle: "Aspirational Living",
      keywords: ["comfort", "style", "everyday", "elevated"],
    },
    caption: "Elevate your everyday with comfort and style",
  },
  {
    assetId: "comp-asset-002",
    competitorId: "comp-001",
    platform: "TikTok",
    format: "video",
    publishDate: "2024-01-15",
    creativeSignals: {
      visualFocus: "person",
      hookStyle: "Quick Transformation",
      narrativeAngle: "Before & After",
      keywords: ["transformation", "quick", "easy", "results"],
    },
    caption: "Quick transformation in 30 seconds",
  },
  {
    assetId: "comp-asset-003",
    competitorId: "comp-001",
    platform: "YouTube",
    format: "video",
    publishDate: "2024-01-20",
    creativeSignals: {
      visualFocus: "scene",
      hookStyle: "Story-Driven",
      narrativeAngle: "Journey Narrative",
      keywords: ["journey", "story", "authentic", "real"],
    },
    caption: "The journey to authentic style",
  },
  {
    assetId: "comp-asset-004",
    competitorId: "comp-002",
    platform: "Instagram",
    format: "image",
    publishDate: "2024-01-12",
    creativeSignals: {
      visualFocus: "product",
      hookStyle: "Product Close-Up",
      narrativeAngle: "Quality Focus",
      keywords: ["glow", "radiant", "natural", "skincare"],
    },
    caption: "Achieve that natural glow",
  },
  {
    assetId: "comp-asset-005",
    competitorId: "comp-002",
    platform: "TikTok",
    format: "video",
    publishDate: "2024-01-18",
    creativeSignals: {
      visualFocus: "person",
      hookStyle: "Tutorial Hook",
      narrativeAngle: "Educational",
      keywords: ["tutorial", "tips", "routine", "skincare"],
    },
    caption: "5-minute skincare routine",
  },
  {
    assetId: "comp-asset-006",
    competitorId: "comp-003",
    platform: "TikTok",
    format: "video",
    publishDate: "2024-01-14",
    creativeSignals: {
      visualFocus: "product",
      hookStyle: "Problem-Solution",
      narrativeAngle: "Problem Solving",
      keywords: ["innovative", "solution", "tech", "smart"],
    },
    caption: "The solution you didn't know you needed",
  },
  {
    assetId: "comp-asset-007",
    competitorId: "comp-003",
    platform: "YouTube",
    format: "video",
    publishDate: "2024-01-22",
    creativeSignals: {
      visualFocus: "scene",
      hookStyle: "Review Format",
      narrativeAngle: "Expert Opinion",
      keywords: ["review", "tested", "honest", "comparison"],
    },
    caption: "Honest review after 30 days",
  },
  {
    assetId: "comp-asset-008",
    competitorId: "comp-004",
    platform: "Instagram",
    format: "image",
    publishDate: "2024-01-16",
    creativeSignals: {
      visualFocus: "person",
      hookStyle: "Motivational",
      narrativeAngle: "Inspiration",
      keywords: ["motivation", "fitness", "strength", "goals"],
    },
    caption: "Strength comes from consistency",
  },
  {
    assetId: "comp-asset-009",
    competitorId: "comp-004",
    platform: "YouTube",
    format: "video",
    publishDate: "2024-01-25",
    creativeSignals: {
      visualFocus: "scene",
      hookStyle: "Workout Demo",
      narrativeAngle: "Instructional",
      keywords: ["workout", "exercise", "training", "fitness"],
    },
    caption: "Full body workout routine",
  },
  {
    assetId: "comp-asset-010",
    competitorId: "comp-005",
    platform: "Instagram",
    format: "image",
    publishDate: "2024-01-11",
    creativeSignals: {
      visualFocus: "product",
      hookStyle: "Food Styling",
      narrativeAngle: "Sensory Appeal",
      keywords: ["delicious", "fresh", "taste", "flavor"],
    },
    caption: "Fresh flavors that excite",
  },
  {
    assetId: "comp-asset-011",
    competitorId: "comp-005",
    platform: "TikTok",
    format: "video",
    publishDate: "2024-01-19",
    creativeSignals: {
      visualFocus: "scene",
      hookStyle: "Recipe Format",
      narrativeAngle: "How-To",
      keywords: ["recipe", "cooking", "easy", "homemade"],
    },
    caption: "Easy recipe in 60 seconds",
  },
  {
    assetId: "comp-asset-012",
    competitorId: "comp-001",
    platform: "Instagram",
    format: "image",
    publishDate: "2024-02-05",
    creativeSignals: {
      visualFocus: "product",
      hookStyle: "Minimalist Showcase",
      narrativeAngle: "Simplicity",
      keywords: ["minimal", "clean", "simple", "essential"],
    },
    caption: "Less is more",
  },
  {
    assetId: "comp-asset-013",
    competitorId: "comp-002",
    platform: "TikTok",
    format: "video",
    publishDate: "2024-02-08",
    creativeSignals: {
      visualFocus: "person",
      hookStyle: "Testimonial Style",
      narrativeAngle: "Social Proof",
      keywords: ["results", "testimonial", "proven", "effective"],
    },
    caption: "Real results from real people",
  },
  {
    assetId: "comp-asset-014",
    competitorId: "comp-003",
    platform: "YouTube",
    format: "video",
    publishDate: "2024-02-12",
    creativeSignals: {
      visualFocus: "product",
      hookStyle: "Feature Highlight",
      narrativeAngle: "Innovation",
      keywords: ["innovative", "features", "advanced", "cutting-edge"],
    },
    caption: "Next-level features revealed",
  },
];

