import { ContentAsset } from "@/types";

export const demoContentAssets: ContentAsset[] = [
  {
    id: "asset-001",
    platform: "YouTube",
    contentType: "video",
    duration: 30,
    creativeFeatures: {
      hookType: "Question Hook",
      pacing: "Fast",
      voiceType: "Energetic",
    },
    publishDate: "2024-01-15",
    views: 125000,
    ctr: 4.2,
    roas: 3.8,
  },
  {
    id: "asset-002",
    platform: "Meta",
    contentType: "video",
    duration: 15,
    creativeFeatures: {
      hookType: "Problem-Solution",
      pacing: "Medium",
      voiceType: "Conversational",
    },
    publishDate: "2024-01-20",
    views: 89000,
    ctr: 5.1,
    roas: 2.9,
  },
  {
    id: "asset-003",
    platform: "TikTok",
    contentType: "video",
    duration: 60,
    creativeFeatures: {
      hookType: "Story Hook",
      pacing: "Slow",
      voiceType: "Narrative",
    },
    publishDate: "2024-01-25",
    views: 210000,
    ctr: 3.8,
    roas: 4.5,
  },
  {
    id: "asset-004",
    platform: "YouTube",
    contentType: "video",
    duration: 45,
    creativeFeatures: {
      hookType: "Shock Value",
      pacing: "Fast",
      voiceType: "Energetic",
    },
    publishDate: "2024-02-01",
    views: 156000,
    ctr: 6.2,
    roas: 3.2,
  },
  {
    id: "asset-005",
    platform: "Meta",
    contentType: "video",
    duration: 20,
    creativeFeatures: {
      hookType: "Question Hook",
      pacing: "Medium",
      voiceType: "Conversational",
    },
    publishDate: "2024-02-05",
    views: 98000,
    ctr: 4.8,
    roas: 5.1,
  },
  {
    id: "asset-006",
    platform: "TikTok",
    contentType: "video",
    duration: 30,
    creativeFeatures: {
      hookType: "Problem-Solution",
      pacing: "Fast",
      voiceType: "Energetic",
    },
    publishDate: "2024-02-10",
    views: 178000,
    ctr: 5.5,
    roas: 4.2,
  },
];

